spring.application.name=Trazabilidad

# ======================================
#pc@pc-Aspire-A315-59:~$ podman run -d \
#  --name mariadbTrazabilidad \
#  -e MYSQL_ROOT_PASSWORD=1234 \
#  -e MYSQL_DATABASE=mi_base \
# -p 3306:3306 \
#  mariadb


# ===============================
# BASE DE DATOS (MariaDB)
# ===============================
spring.datasource.url=jdbc:mariadb://host.containers.internal:3306/mi_base
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# JWT
# ===============================
jwt.secret=c3e624fae7a048a3563d5b29568196e0564aebddab4b9ba9717dcace82efaa10
jwt.expiration=86400
